# Generated by Django 5.0.3 on 2024-03-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
