# Generated by Django 5.0.3 on 2024-03-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_product_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
